# Generated by Django 2.1.5 on 2019-02-28 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InstabotMV', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='allusers',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
