# Generated by Django 2.1.5 on 2019-02-12 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InstabotMV', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='thread',
            options={'verbose_name': 'thread', 'verbose_name_plural': 'threads'},
        ),
        migrations.AddField(
            model_name='creds',
            name='imgUrl',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
