# Generated by Django 2.1.1 on 2018-12-21 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InstabotMV', '0002_locatelist_taglist_uslist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taglist',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='uslist',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
