# Generated by Django 2.1.5 on 2019-02-15 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InstabotMV', '0002_auto_20190212_2050'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='back',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='ghost',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='unfollow',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
