# Generated by Django 2.1.1 on 2019-03-01 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InstabotMV', '0002_auto_20190301_0905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creds',
            name='ceiling',
            field=models.BooleanField(default=False),
        ),
    ]
