# Generated by Django 2.1.5 on 2019-02-06 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InstabotMV', '0002_lastlogin'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lastlogin',
            options={'verbose_name': 'lastLogin', 'verbose_name_plural': 'lastLogin'},
        ),
        migrations.AddField(
            model_name='task',
            name='active',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
