# Generated by Django 2.1.4 on 2019-01-15 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('InstabotMV', '0003_auto_20181221_1215'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChildTag',
            fields=[
                ('tag_name', models.CharField(max_length=100)),
                ('hashtag_id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Features',
            fields=[
                ('id_feature', models.IntegerField(primary_key=True, serialize=False)),
                ('feature_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='HashtagList',
            fields=[
                ('id_tag', models.IntegerField(primary_key=True, serialize=False)),
                ('catalogo', models.CharField(max_length=200)),
                ('hashtag_names', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='List_Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insta_tag', models.CharField(max_length=100)),
                ('id_name', models.IntegerField()),
                ('num_catalog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InstabotMV.HashtagList')),
            ],
        ),
        migrations.RemoveField(
            model_name='taglist',
            name='user',
        ),
        migrations.AddField(
            model_name='media',
            name='owner_name',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Taglist',
        ),
        migrations.AddField(
            model_name='childtag',
            name='dad_tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InstabotMV.HashtagList'),
        ),
    ]
