# Generated by Django 2.1.5 on 2019-02-15 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('InstabotMV', '0003_auto_20190215_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lastlogin',
            name='cred',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='InstabotMV.Creds'),
        ),
    ]
