# Generated by Django 2.1.1 on 2019-03-01 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InstabotMV', '0003_auto_20190301_0914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='allusers',
            field=models.BooleanField(default=False),
        ),
    ]
