# Generated by Django 2.1.5 on 2019-02-15 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('InstabotMV', '0005_auto_20190215_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lastlogin',
            name='cred',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InstabotMV.Creds'),
        ),
    ]
