# Generated by Django 2.1.5 on 2019-02-15 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('InstabotMV', '0006_auto_20190215_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lastlogin',
            name='cred',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='InstabotMV.Creds'),
        ),
    ]
